
export const moviesData = [
    { title: "Princess Frog", id:"1", trailer:"https://youtu.be/uQBy6jqbmlU", description:"A waitress, desperate to fulfill her dreams as a restaurant owner, is set on a journey to turn a frog prince back into a human being.", rate: "4", Img: "https://i.pinimg.com/originals/8b/9e/8c/8b9e8c80fc4929ee384ffd234bc7acb7.jpg",},
    {title: "Frozen",id:"2", trailer:"https://youtu.be/Zi4LMpSDccc",description:" the newly crowned Queen Elsa accidentally uses her power to turn things into ice to curse her home in infinite winter.",rate: "2",Img:"https://runt-of-the-web.com/wordpress/wp-content/uploads/2014/08/frozen.jpg",},
    {title: "Beauty and the beast", id:"3",trailer:" https://youtu.be/OvW_L8sTu5E",description:"A selfish Prince is cursed to become a monster for the rest of his life, unless he learns to fall in love with a beautiful young woman he keeps prisoner.",rate: "2",Img:"https://i.pinimg.com/originals/6d/16/2f/6d162f9417d607b0f953010c1764f972.jpg",},
    {title: "Pocahontas",id:"4", trailer:" https://youtu.be/Z0oi7Qpp6W4",description:"An English soldier and the daughter of an Algonquin chief share a romance when English colonists invade seventeenth century Virginia.",rate: "1",Img:"https://i.pinimg.com/originals/1c/c6/4c/1cc64c3c7936760675bb4a65cf0ace54.jpg",},
    {title: "Le Roi Lion",id:"5", trailer:"https://youtu.be/-KfIYw-D4Iw",description:"Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself",rate: "3",Img:"https://i.pinimg.com/originals/8a/c2/32/8ac232bf0c11fe6a93872c006cba374b.jpg",},
    {title: "Snow White",id:"6", trailer:"https://youtu.be/5fzZFQBXSLM",description:"Exiled into the dangerous forest by her wicked stepmother, a princess is rescued by seven dwarf miners who make her part of their household. ",rate: "5",Img:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLdGskD-ZomoftERM1OtE457ersKZJZ2mQDd3RAQWirQYXrZemxLwWRxz_JrjT0ICeNaE&usqp=CAU",},
    {title: "Aladdin",id:"7", trailer:"https://youtu.be/9g5knnlF7Zo",description:"a street urchin in the Arabian city of Agrabah, and his monkey Abu meet Princess Jasmine, who has snuck away from her sheltered life in the palace ",rate: "5",Img: "https://ohmy.disney.com/wp-content/uploads/2014/01/31-aladdin.jpg",},
  ];